In [ ]:
import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd
import numpy as np
import os
import re
import warnings
warnings.filterwarnings("ignore")
from google.colab import drive
# drive.mount('/content/drive')
# os.chdir('/content/drive/MyDrive/Bot/Parsing')
from tqdm import tqdm
from urllib.parse import urljoin, urlparse
import time
!pip install fake_useragent
from fake_useragent import UserAgent
UserAgent().chrome
from multiprocessing import Pool
!pip install google-colab-selenium
import google_colab_selenium as gs
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import ActionChains

Collecting fake_useragent
  Downloading fake_useragent-2.2.0-py3-none-any.whl.metadata (17 kB)
Downloading fake_useragent-2.2.0-py3-none-any.whl (161 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.7/161.7 kB 10.8 MB/s eta 0:00:00
Installing collected packages: fake_useragent
Successfully installed fake_useragent-2.2.0
Collecting google-colab-selenium
  Downloading google_colab_selenium-1.0.17-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: notebook>=6.5.7 in /usr/local/lib/python3.12/dist-packages (from google-colab-selenium) (6.5.7)
Collecting selenium (from google-colab-selenium)
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (3.1.6)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (6.5.1)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (26.2.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (25.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (5.7.1)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (5.9.1)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (7.4.9)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (0.2.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (7.17.0)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (1.6.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (6.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (1.3.3)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium->google-colab-selenium) (2026.2.25)
Collecting trio<1.0,>=0.31.0 (from selenium->google-colab-selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium->google-colab-selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium->google-colab-selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium->google-colab-selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium->google-colab-selenium) (1.9.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client<8,>=5.3.4->notebook>=6.5.7->google-colab-selenium) (0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client<8,>=5.3.4->notebook>=6.5.7->google-colab-selenium) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.6.1->notebook>=6.5.7->google-colab-selenium) (4.9.4)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.10.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (26.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (2.20.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=6.5.7->google-colab-selenium) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=6.5.7->google-colab-selenium) (4.26.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.12/dist-packages (from terminado>=0.8.3->notebook>=6.5.7->google-colab-selenium) (0.7.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->google-colab-selenium) (26.1.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium->google-colab-selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->google-colab-selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium->google-colab-selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->google-colab-selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium->google-colab-selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->google-colab-selenium) (1.7.1)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=6.5.7->google-colab-selenium) (25.1.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (7.34.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (0.2.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (5.9.5)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (1.4.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (3.0.52)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (4.9.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=6.5.7->google-colab-selenium) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=6.5.7->google-colab-selenium) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=6.5.7->google-colab-selenium) (0.30.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (2.14.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->jupyter-client<8,>=5.3.4->notebook>=6.5.7->google-colab-selenium) (1.17.0)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium->google-colab-selenium) (0.16.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=6.5.7->google-colab-selenium) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (2.8.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=6.5.7->google-colab-selenium) (3.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.8.6)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (4.13.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (7.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.6.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (25.10.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.4.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (2025.3)
Downloading google_colab_selenium-1.0.17-py3-none-any.whl (10 kB)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 75.0 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 26.3 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 10.5 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 57.7 MB/s eta 0:00:00
Installing collected packages: sortedcontainers, wsproto, urllib3, outcome, jedi, trio, trio-websocket, selenium, google-colab-selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed google-colab-selenium-1.0.17 jedi-0.19.2 outcome-1.3.0.post0 selenium-4.41.0 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 wsproto-1.3.2

#titles

In [ ]:
def write_title_data(data):
    with open('imdb_movies.csv','a') as f:
        writer = csv.writer(f)
        writer.writerow((
            data['url'],
            data['title'],
            data['orig_title'],
            data['movie_type'],
            data['year'],
            data['age_limit'],
            data['m_time'],
            data['genres'],
            data['episodes'],
            data['imdb'],
            data['metascore'],
            data['epi_refs'],
            data['cast_refs'],
            data['genre_refs'],
            data['award_refs'],
            data['plot']
            ))

In [ ]:
def write_error_log(i, url, error_log):
    with open('error_log.txt', 'a') as f:
        f.write(f'{i} | {url} | {error_log} \n')
    with open('error_urls.txt', 'a') as f:
        f.write(url + '\n')

In [ ]:
def get_movie_data(html, url, ind):
    urls = []
    imdb_url = 'https://www.imdb.com'
    mlist = ['TV Mini Series', 'TV Short', 'TV Movie', 'TV Special', 'TV Series']
    soup = BeautifulSoup(html, 'html.parser', from_encoding='utf-8')
    try:
        elem = soup.find('section', class_='ipc-page-background ipc-page-background--base sc-afa4bed1-0 iMxoKo')
        try:
            title_elem = elem.find('div', class_='sc-70a366cc-0 bxYZmb')
            title = title_elem.find('h1').text.strip()
            try:
                orig_title = title_elem.find('div', class_='sc-ec65ba05-1 fUCCIx').text.split('Original title:')[-1].strip()
            except Exception as e:
                orig_title = ''
            try:
                title_info = title_elem.find('ul').findChildren('li')
                movie_type, year, age_limit, m_time = '', '', '', ''
                if title_info:
                    for info in title_info:
                        info = info.text.strip()
                        if info in mlist:
                            movie_type = info
                        if re.match(r'\(*\d{4}–*\d* *\)*', info):
                            year = info
                        if re.match(r'(\d{1,3}h *\d* *m*i*n*)|(\d{1,4} *mi*n*)', info):
                            m_time = info
                        if info in ['Passed', 'Approved','Unrated'] or re.match('\d{1,2}\+', info)\
                         or (re.match(r'[A-Z]{1,2}(\-|\/)*[A-Z0-9]*\-*[A-Z0-9]*', info) and info not in mlist):
                           age_limit = info
                    if movie_type == '':
                        movie_type = 'Movie'
                else:
                    movie_type, year, age_limit, m_time = ['']*4
            except Exception as e:
                error_log = f'Title info exception: {e}, Title: {title}'
                print(error_log)
                write_error_log(ind, url, error_log)
                movie_type, year, age_limit, m_time = ['']*4
        except Exception as e:
            error_log = f'Title element exception: {e}'
            print(error_log)
            write_error_log(ind, url, error_log)
            title, orig_title, movie_type, year, age_limit, m_time = ['']*6
        try:
            plot_elems = soup.find('div', class_='sc-9a2a0028-6 zHrZh')
            elem_genres = plot_elems.find('div', class_='ipc-chip-list__scroller').find_all('a')
            genres = ', '.join([a.text.strip() for a in elem_genres])
            genre_refs = ', '.join([imdb_url + a['href'] for a in elem_genres])
            elem_plot = plot_elems.find('p').find_all('span')
            plot = elem_plot[-1].text.strip()
        except Exception as e:
            try:
                plot_elems = soup.find('div', class_='sc-9a2a0028-10 dFokEJ')
                elem_genres = plot_elems.find('div', class_='ipc-chip-list__scroller').find_all('a')
                genres = ', '.join([a.text.strip() for a in elem_genres])
                genre_refs = ', '.join([imdb_url + a['href'] for a in elem_genres])
                elem_plot = plot_elems.find('p').find_all('span')
                plot = elem_plot[-1].text.strip()
            except Exception as e:
                error_log = f'Plot block exception: {e}, Title: {title}'
                print(error_log)
                write_error_log(ind, url, error_log)
                genres, plot, genre_refs = '', '', ''

        try:
            rate_elems = soup.find('div', class_='sc-9a2a0028-11 ketnsO')
            try:
                rating = rate_elems.find('div', 'sc-d541859f-2 kxphVf')
                imdb = float(rating.find_all('span')[0].text.strip())
            except:
                imdb = ''
            try:
                rate = rate_elems.find('ul', 'ipc-inline-list sc-b782214c-0 bllRjU baseAlt')
                metascore = int(rate.find_all('li')[2].find('span',class_='score').text.strip())
            except:
                metascore = ''
        except Exception as e:
            #print(f'Rating block exception: {e}, Title: {title}')
            imdb, metascore = '', ''
        try:
            award_elems = soup.find('section', class_='ipc-page-section',
                                     attrs = {'cel_widget_id':'StaticFeature_Awards'})
            award_refs = imdb_url + award_elems.find('ul').find('li').find('a')['href']
        except Exception:
            award_refs = ''
        try:
            ep_elems = soup.find('section', class_='ipc-page-section',
                                  attrs = {'data-testid':'Episodes'})
            epi_elems = ep_elems.find('h3')
            if epi_elems:
                epi_refs = imdb_url + ep_elems.find('div', class_='ipc-title').find('a')['href']
                episodes = int(epi_elems.find_all('span')[-1].text.strip())
            else:
                episodes, epi_refs  = '', ''
        except Exception as e:
            #print(f'Episode block exception: {e}, Title: {title}')
            episodes, epi_refs  = '', ''
        try:
            cast_elems = soup.find('section', class_='ipc-page-section',
                                    attrs = {'data-testid':'title-cast'})
            if cast_elems:
                cast_refs = imdb_url + cast_elems.find('div', class_='ipc-title__wrapper').find('a')['href']
            else:
                cast_refs = ''
        except Exception as e:
            error_log = f'Cast block exception: {e}, Title: {title}'
            print(error_log)
            write_error_log(ind, url, error_log)
            cast_refs = ''
    except Exception as e:
        error_log = f'Movie block exception: {e}'
        print(error_log)
        write_error_log(ind, url, error_log)
        title, movie_type, year, age_limit, m_time, genres, plot, episodes = ['']*8
        epi_refs, cast_refs, genre_refs, imdb, orig_title, award_refs, metascore = ['']*7


    d = {'url':url, 'title': title, 'orig_title': orig_title, 'movie_type': movie_type,
         'year': year, 'age_limit': age_limit, 'm_time': m_time, 'genres': genres,
         'episodes': episodes, 'imdb': imdb, 'metascore':metascore,
         'epi_refs': epi_refs, 'cast_refs': cast_refs, 'genre_refs': genre_refs,
         'award_refs':award_refs, 'plot': plot}
    #print(d)
    write_title_data(d)

#continue

In [ ]:
df = pd.read_csv('imdb_movies.csv', names = ['url', 'title']+[str(i) for i in range(14)])
df.tail()

,url,title,0,1,2,3,4,5,6,7,8,9,10,11,12,13
103654,https://www.imdb.com/title/tt14039724/?ref_=sr...,Ichata Vahanamulu Nilupa Radu,Ichata Vahanumulu Niluparadu,Movie,2021,NaN,2h 31m,"Drama, Mystery, Romance, Thriller",NaN,5.7,NaN,NaN,https://www.imdb.com/title/tt14039724/fullcred...,https://www.imdb.com/interest/in0000076/?ref_=...,https://www.imdb.com/title/tt14039724/awards/?...,"Arun is an architect who has a loving mother, ..."
103655,https://www.imdb.com/title/tt30472557/?ref_=sr...,Chainsaw Man - The Movie: Reze Arc,Gekijô-ban Chensô Man Reze-hen,Movie,2025,NaN,NaN,"Adult Animation, Anime, Shōnen, Supernatural F...",NaN,NaN,NaN,NaN,https://www.imdb.com/title/tt30472557/fullcred...,https://www.imdb.com/interest/in0000025/?ref_=...,NaN,"Denji encounters a new romantic interest, Reze..."
103656,https://www.imdb.com/title/tt1185616/?ref_=sr_...,Waltz with Bashir,Vals Im Bashir,Movie,2008,R,1h 30m,"Adult Animation, Computer Animation, Docudrama...",NaN,8.0,91.0,NaN,https://www.imdb.com/title/tt1185616/fullcredi...,https://www.imdb.com/interest/in0000025/?ref_=...,https://www.imdb.com/title/tt1185616/awards/?r...,An Israeli film director interviews fellow vet...
103657,https://www.imdb.com/title/tt9182964/?ref_=sr_...,The Reckoning,NaN,Movie,2020,Not Rated,1h 50m,"Adventure, Drama, Horror",NaN,4.8,31.0,NaN,https://www.imdb.com/title/tt9182964/fullcredi...,https://www.imdb.com/interest/in0000012/?ref_=...,https://www.imdb.com/title/tt9182964/awards/?r...,"Grace, a young widow haunted by the recent sui..."
103658,https://www.imdb.com/title/tt0058479/?ref_=sr_...,The Pleasure Seekers,NaN,Movie,1964,Approved,1h 47m,"Comedy, Musical, Romance",NaN,NaN,NaN,NaN,https://www.imdb.com/title/tt0058479/fullcredi...,https://www.imdb.com/interest/in0000034/?ref_=...,https://www.imdb.com/title/tt0058479/awards/?r...,Three American lovelies rooming together in Ma...

In [ ]:
df[df.title == "The Fox"]

,url,title,0,1,2,3,4,5,6,7,8,9,10,11,12,13
5004,https://www.imdb.com/title/tt14439178/?ref_=sr...,The Fox,Der Fuchs,Movie,2022,NaN,1h 58m,"Drama, History, War",NaN,7.1,NaN,NaN,https://www.imdb.com/title/tt14439178/fullcred...,https://www.imdb.com/interest/in0000076/?ref_=...,https://www.imdb.com/title/tt14439178/awards/?...,"At the dawn of WW2, a young soldier encounters..."
13648,https://www.imdb.com/title/tt12525406/?ref_=sr...,The Fox,NaN,NaN,NaN,NaN,NaN,Comedy,NaN,NaN,NaN,NaN,https://www.imdb.com/title/tt12525406/fullcred...,https://www.imdb.com/interest/in0000034/?ref_=...,NaN,"In this black comedic folktale, an affable fox..."
73803,https://www.imdb.com/title/tt14439178/?ref_=sr...,The Fox,Der Fuchs,Movie,2022,NaN,1h 58m,"Drama, History, War",NaN,7.1,NaN,NaN,https://www.imdb.com/title/tt14439178/fullcred...,https://www.imdb.com/interest/in0000076/?ref_=...,https://www.imdb.com/title/tt14439178/awards/?...,"At the dawn of WW2, a young soldier encounters..."

In [ ]:
df['13'].str.len().max()

382.0

In [ ]:
df['10'].value_counts()

10
https://www.imdb.com/title/tt32384391/fullcredits/?ref_=tt_cst_sm    11
https://www.imdb.com/title/tt3061046/fullcredits/?ref_=tt_cst_sm     11
https://www.imdb.com/title/tt1710308/fullcredits/?ref_=tt_cst_sm     10
https://www.imdb.com/title/tt2742544/fullcredits/?ref_=tt_cst_sm     10
https://www.imdb.com/title/tt11165358/fullcredits/?ref_=tt_cst_sm    10
                                                                     ..
https://www.imdb.com/title/tt0031619/fullcredits/?ref_=tt_cst_sm      1
https://www.imdb.com/title/tt21998526/fullcredits/?ref_=tt_cst_sm     1
https://www.imdb.com/title/tt6982604/fullcredits/?ref_=tt_cst_sm      1
https://www.imdb.com/title/tt21867362/fullcredits/?ref_=tt_cst_sm     1
https://www.imdb.com/title/tt0058479/fullcredits/?ref_=tt_cst_sm      1
Name: count, Length: 54538, dtype: int64

In [ ]:
df[df['9'].str.len()==df['9'].str.len().max()]

AttributeError: Can only use .str accessor with string values!

In [ ]:
genre_urls = []
for i in range(len(df)):
    if str(df['11'][i]) != 'nan':
        urls = df['11'][i].split(', ')
        for u in urls:
            url = u.split('?')[0]
            if url not in genre_urls:
                genre_urls.append(url)

In [ ]:
genre_urls[:10], len(genre_urls), len(set(genre_urls))

(['https://www.imdb.com/interest/in0000177/',
  'https://www.imdb.com/interest/in0000159/',
  'https://www.imdb.com/interest/in0000001/',
  'https://www.imdb.com/interest/in0000076/',
  'https://www.imdb.com/interest/in0000162/',
  'https://www.imdb.com/interest/in0000186/',
  'https://www.imdb.com/interest/in0000152/',
  'https://www.imdb.com/interest/in0000052/',
  'https://www.imdb.com/interest/in0000139/',
  'https://www.imdb.com/interest/in0000026/'],
 212,
 212)

In [ ]:
set_genres =  list(set(genre_urls))
with open('genre_urls.txt', 'w') as f:
    for i in set_genres:
        f.write(i + '\n')

#genres

In [ ]:
with open('genre_urls.txt', 'r') as f:
    genre_urls = f.readlines()
genre_urls = [u.strip() for u in genre_urls]

In [ ]:
def write_genre_data(data):
    with open('imdb_genres.csv','a') as f:
        writer = csv.writer(f)
        writer.writerow((
            data['url'],
            data['genre'],
            data['descr']
            ))

In [ ]:
def write_genre_error_log(i, url, error_log):
    with open('error_genre_log.txt', 'a') as f:
        f.write(f'{i} | {url} | {error_log} \n')
    with open('error_genre_urls.txt', 'a') as f:
        f.write(url + '\n')

In [ ]:
def get_genre_data(html, ind, url):
    imdb_url = 'https://www.imdb.com'
    soup = BeautifulSoup(html, 'html.parser', from_encoding='utf-8')
    try:
        block = soup.find('div', class_='ipc-page-content-container ipc-page-content-container--center sc-986b349d-0 gBOYNf')
        block_d = block.find('div', class_='sc-81d15d15-0 cOmmee')
        genre_elem = block_d.find('div', class_='sc-81d15d15-2 kDKCev')
        try:
            genre = genre_elem.find('div', class_='ipc-title').find('h3').text.strip()
        except Exception as e:
            error_log = f'Genre name block exception: {e}, url: {url}'
            print(error_log)
            write_genre_error_log(ind, url, error_log)
            genre = ''
        try:
            descr = genre_elem.find('div', class_='ipc-overflowText').find('div', class_='ipc-html-content-inner-div').text.strip()
        except Exception as e:
            error_log = f'Description block exception: {e}, Genre: {genre}'
            print(error_log)
            write_genre_error_log(ind, url, error_log)
            descr = ''
    except Exception as e:
        error_log = f'Content block Exception: {e}, url: {url}'
        print(error_log)
        write_genre_error_log(ind, url, error_log)
        genre, descr = '', ''
    d = {'url': url, 'genre':genre, 'descr':descr}
    #print(d)
    write_genre_data(d)

In [ ]:
#drama_titles.append('https://www.imdb.com/title/tt0808357/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_lust')
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
for i in range(len(genre_urls)):
    url = genre_urls[i]
    response = requests.get(url,
                            headers={'Accept-Language': 'en-US,en;q=0.9',
                                          #'User-Agent': UserAgent().chrome
                                     'User-Agent':user_agent})
    #print(response.headers.get('Content-Type'))
    if i % 10 == 0:
        print(url)
    html = response.content.decode('utf-8')
    get_genre_data(html, i, url)
    time.sleep(1)

https://www.imdb.com/interest/in0000180/
https://www.imdb.com/interest/in0000105/
https://www.imdb.com/interest/in0000052/
https://www.imdb.com/interest/in0000135/
https://www.imdb.com/interest/in0000129/
https://www.imdb.com/interest/in0000061/
https://www.imdb.com/interest/in0000068/
https://www.imdb.com/interest/in0000087/
https://www.imdb.com/interest/in0000041/
https://www.imdb.com/interest/in0000028/
https://www.imdb.com/interest/in0000099/
https://www.imdb.com/interest/in0000152/
https://www.imdb.com/interest/in0000163/
Content block Exception: 'NoneType' object has no attribute 'find', url: https://www.imdb.com/search/title/
https://www.imdb.com/interest/in0000190/
https://www.imdb.com/interest/in0000128/
https://www.imdb.com/interest/in0000054/
https://www.imdb.com/interest/in0000079/
https://www.imdb.com/interest/in0000022/
https://www.imdb.com/interest/in0000091/
https://www.imdb.com/interest/in0000116/
https://www.imdb.com/interest/in0000168/
https://www.imdb.com/interest/in0000130/

#Cast

##prep

In [ ]:
df = pd.read_csv('imdb_movies.csv', names = ['url', 'title']+[str(i) for i in range(14)])
df.tail(3)

,url,title,0,1,2,3,4,5,6,7,8,9,10,11,12,13
103656,https://www.imdb.com/title/tt1185616/?ref_=sr_...,Waltz with Bashir,Vals Im Bashir,Movie,2008,R,1h 30m,"Adult Animation, Computer Animation, Docudrama...",NaN,8.0,91.0,NaN,https://www.imdb.com/title/tt1185616/fullcredi...,https://www.imdb.com/interest/in0000025/?ref_=...,https://www.imdb.com/title/tt1185616/awards/?r...,An Israeli film director interviews fellow vet...
103657,https://www.imdb.com/title/tt9182964/?ref_=sr_...,The Reckoning,NaN,Movie,2020,Not Rated,1h 50m,"Adventure, Drama, Horror",NaN,4.8,31.0,NaN,https://www.imdb.com/title/tt9182964/fullcredi...,https://www.imdb.com/interest/in0000012/?ref_=...,https://www.imdb.com/title/tt9182964/awards/?r...,"Grace, a young widow haunted by the recent sui..."
103658,https://www.imdb.com/title/tt0058479/?ref_=sr_...,The Pleasure Seekers,NaN,Movie,1964,Approved,1h 47m,"Comedy, Musical, Romance",NaN,NaN,NaN,NaN,https://www.imdb.com/title/tt0058479/fullcredi...,https://www.imdb.com/interest/in0000034/?ref_=...,https://www.imdb.com/title/tt0058479/awards/?r...,Three American lovelies rooming together in Ma...

In [ ]:
dt = df[['10', '1', '2']].copy()
dt.copy()

                                                       10          1     2
0       https://www.imdb.com/title/tt0113481/fullcredi...      Movie  1995
1       https://www.imdb.com/title/tt1982229/fullcredi...  TV Series  2011
2       https://www.imdb.com/title/tt0041699/fullcredi...      Movie  1949
3       https://www.imdb.com/title/tt14344936/fullcred...      Movie  2020
4       https://www.imdb.com/title/tt0078490/fullcredi...      Movie  1978
...                                                   ...        ...   ...
103654  https://www.imdb.com/title/tt14039724/fullcred...      Movie  2021
103655  https://www.imdb.com/title/tt30472557/fullcred...      Movie  2025
103656  https://www.imdb.com/title/tt1185616/fullcredi...      Movie  2008
103657  https://www.imdb.com/title/tt9182964/fullcredi...      Movie  2020
103658  https://www.imdb.com/title/tt0058479/fullcredi...      Movie  1964

[103659 rows x 3 columns]

In [ ]:
dt = dt[(dt['1'].isna()==False)&(dt['10'].isna()==False)]

In [ ]:
dt = dt.drop_duplicates(keep='first')

In [ ]:
dt.to_csv('cast_urls.csv', index=False, header=False)

In [ ]:
dt['10'].str.split('?')

In [ ]:
cast_urls = [url.split('?')[0] for url in df['10'].values if url is not np.nan]

In [ ]:
cast_urls = list(set(cast_urls))

##parser

In [ ]:
dt = pd.read_csv('cast_urls.csv', names=['url', 'mtype', 'year'])
dt.head(3)

                                                 url      mtype  year
0  https://www.imdb.com/title/tt0113481/fullcredi...      Movie  1995
1  https://www.imdb.com/title/tt1982229/fullcredi...  TV Series  2011
2  https://www.imdb.com/title/tt0041699/fullcredi...      Movie  1949

In [ ]:
def write_cast_data(data):
    with open('imdb_casts.csv','a') as f:
        writer = csv.writer(f)
        writer.writerow((
            data['url'],
            data['title'],
            data['department'],
            data['name'],
            data['position'],
            data['comment'],
            data['episodes'],
            data['year'],
            data['credited'],
            data['rating'],
            data['name_ref']
            ))

In [ ]:
def write_cast_error_log(i, url, error_log):
    with open('error_cast_log.txt', 'a') as f:
        f.write(f'{i} | {url} | {error_log} \n')
    with open('error_cast_urls.txt', 'a') as f:
        f.write(url + '\n')

In [ ]:
def separated_position(position):
    """
    Separates position, comment and credited from a string

    Args:
        position (str): full line of position/role.

    Returns:
       data (list): list of dicts in separated lines
    """
    #Checking whether person worked for several positions
    data = []
    comment = ''
    if '/ ...' in position:
        position = position.replace('/ ...', '').strip()
    if ' / ' not in position:
        if ':' in position:
            pos = position.split(':')[0]
            comment = ', '.join(position.split(':')[1:])
            position, comment = pos.strip(), comment.strip()
        position, comment, credited = separated_position_comments_credits(position, comment)
        if 'uncredited' in comment.lower():
            comment = comment.replace('uncredited', '').replace('(', '').replace(')', '').strip()
            credited = 'Uncredited'
        elif '(as ' in comment.lower():
            comment, credited = comment.split('(as ')
            credited = credited.replace(')', '').strip()
            comment = comment.strip()
        data.append({'position':position, 'comment':comment, 'credited':credited})
    else:
        sep_position = position.split(' / ')
        for pos in sep_position:
            if ':' in pos:
                position = pos.split(':')[0]
                comment = ', '.join(pos.split(':')[1:])
                position, comment = position.strip(), comment.strip()
                position, comment, credited = separated_position_comments_credits(position, comment)
                if 'uncredited' in comment.lower():
                    comment = comment.replace('uncredited', '').replace('(', '').replace(')', '').strip()
                    credited = 'Uncredited'
                elif '(as ' in comment.lower():
                    comment, credited = comment.split('(as ')
                    credited = credited.replace(')', '').strip()
                    comment = comment.strip()
                data.append({'position':position, 'comment':comment, 'credited':credited})
            else:
                position, comment = pos.strip(), ''
                position, comment, credited = separated_position_comments_credits(position, comment)
                if 'uncredited' in comment.lower():
                    comment = comment.replace('uncredited', '').replace('(', '').replace(')', '').strip()
                    credited = 'Uncredited'
                elif '(as ' in comment.lower():
                    comment, credited = comment.split('(as ')
                    credited = credited.replace(')', '').strip()
                    comment = comment.strip()
                data.append({'position':position, 'comment':comment, 'credited':credited})
    return data

def separated_position_comments_credits(position, comment):
    credited = ''
    #Checking whether the person is uncredited
    if 'uncredited' in position.lower():
        position = position.replace('uncredited', '').replace('(', '').replace(')', '').strip()
        credited = 'Uncredited'
    #Checking whether the person is credited under other name
    elif '(as ' in position.lower():
        position, credited = position.split('(as ')
        credited = credited.replace(')', '').strip()
        position = position.strip()
    if '(' in position:
        position = position.replace(')', '').replace('(', '').strip()
    else:
        position = position.strip()
    return position, comment, credited

def separated_episodes(episodes, year):
    if 'unknown episodes' not in episodes:
        try:
            episodes, year = episodes.split(', ')
            episodes = episodes.replace('(', '').replace(')', '').strip()
            year = year.replace('(', '').replace(')', '').strip()
        except Exception as e:
            episodes = episodes.replace('(', '').replace(')', '').strip()
            year = year.replace('(', '').replace(')', '').strip()
    else:
        episodes = 'unknown episodes'
    return episodes, year

In [ ]:
def parse_series(cast_table, cast_h4, imdb_url, title, year, ind):
    full_list = []
    for i in range(len(cast_table)):
        h4, table = cast_h4[i], cast_table[i]
        department = h4.text.strip().replace('\n      ', '').replace('\n', '')
        info = table.find_all('tr')
        if 'Cast' in department and 'Casting' not in department:
            for j in range(1, len(info)):
                tds = info[j].find_all('td')
                if len(tds)>1:
                    rating = j
                    try:
                        name = tds[1].find('a').text.strip()
                        name_ref = imdb_url + tds[1].find('a')['href']
                    except Exception as e:
                        error_msg = f'Name block exception: url={url}, dep={department} | {e}'
                        write_cast_error_log(ind, url, error_msg)
                        print(ind, error_msg)
                    try:
                        href = tds[3].find_all('a')
                        episodes = href[1].text
                        position = tds[3].text.replace(episodes, '')
                        episodes, year = separated_episodes(episodes, year)
                        data = separated_position(position)
                    except Exception as e:
                        try:
                            href = tds[3].find_all('a')
                            episodes = href[0].text
                            data = [{'position':'', 'comment':'', 'credited':''}]
                            episodes, year = separated_episodes(episodes, year)
                        except Exception as e:
                            error_msg = f'Position block exception: url={url}, dep={department}, name={name} | {e}'
                            write_cast_error_log(ind, url, error_msg)
                            print(ind, error_msg)
                            data = [{'position':'', 'comment':'', 'credited':''}]
                            episodes = ''
                    for dct in data:
                        d = {'url':url, 'title':title, 'department': department,
                            'name':name, 'position':dct['position'],
                            'comment': dct['comment'], 'episodes':episodes,
                            'year':year, 'credited': dct['credited'],
                            'rating':rating, 'name_ref':name_ref}
                        full_list.append(d)
                else:
                    continue
        else:
            for j in range(len(info)):
                rating = j + 1
                tds = info[j].find_all('td')
                name = tds[0].find('a').text.strip()
                name_ref = imdb_url + tds[0].find('a')['href']
                full_position = tds[2].text.strip()
                try:
                    m = re.search(r'\(*\d* episodes*,* *\d*-*\d*\)*', full_position)
                    if m:
                        episodes = m.group(0)
                    elif '(unknown episodes)' in full_position:
                        episodes = 'unknown episodes'
                    else:
                        episodes = ''
                    position = full_position.replace(episodes, '').strip()
                    data = separated_position(position)
                    episodes, year = separated_episodes(episodes, year)
                    for dct in data:
                        d = {'url':url, 'title':title, 'department': department,
                            'name':name, 'position':dct['position'],
                            'comment': dct['comment'], 'episodes':episodes,
                            'year':year, 'credited': dct['credited'],
                            'rating':rating, 'name_ref':name_ref}
                        full_list.append(d)
                except Exception as e:
                    error_msg = f'Position block exception: url={url}, dep={department}, name={name} | {e}'
                    write_cast_error_log(ind, url, error_msg)
                    print(ind, error_msg)
                    continue
    return full_list

In [ ]:
def parse_movies(cast_table, cast_h4, imdb_url, title, year, ind):
    full_list = []
    for i in range(len(cast_table)):
        h4, table = cast_h4[i], cast_table[i]
        department = h4.text.strip().replace('\n      ', '').replace('\n', '')
        info = [tr for tr in table.find_all('tr') if tr.find('td', class_='name') is not None or\
                tr.find('td', class_='primary_photo') is not None]
        if 'Cast' in department and 'Casting' not in department:
            for j in range(len(info)):
                try:
                    row = info[j]
                    tds = row.find_all('td')
                    if len(tds)>1:
                        rating = j
                        name = tds[1].find('a').text.strip()
                        name_ref = imdb_url + tds[1].find('a')['href']
                        try:
                            position = tds[3].text.strip()
                            episodes = ''
                        except Exception as e:
                            position, episodes = '', ''
                        data = separated_position(position)
                        for dct in data:
                            d = {'url':url, 'title':title, 'department': department,
                                'name':name, 'position':dct['position'],
                                'comment': dct['comment'], 'episodes':episodes,
                                'year':year, 'credited': dct['credited'],
                                'rating':rating, 'name_ref':name_ref}
                            full_list.append(d)
                    else:
                        continue
                except Exception as e:
                    error_msg = f'Movie Actors Exception: url={url}, dep={department}, name={name} | {e}'
                    write_cast_error_log(ind, url, error_msg)
                    print(ind, error_msg)
                    continue
        else:
            for j in range(len(info)):
                try:
                    rating = j + 1
                    tds = info[j].find_all('td')
                    name = tds[0].find('a').text.strip()
                    name_ref = imdb_url + tds[0].find('a')['href']
                    try:
                        position = tds[2].text.strip()
                    except Exception as e:
                        position = ''
                    episodes = ''
                    data = separated_position(position)
                    for dct in data:
                        d = {'url':url, 'title':title, 'department': department,
                            'name':name, 'position':dct['position'],
                            'comment': dct['comment'], 'episodes':episodes,
                            'year':year, 'credited': dct['credited'],
                            'rating':rating, 'name_ref':name_ref}
                        full_list.append(d)
                except Exception as e:
                    error_msg = f'Movie Cast Exception: url={url}, dep={department}, name={name} | {e}'
                    write_cast_error_log(ind, url, error_msg)
                    print(ind, error_msg)
                    continue
    return full_list

In [ ]:
def get_cast_data(html, url, mtype, year, ind):
    imdb_url = 'https://www.imdb.com'
    soup = BeautifulSoup(html, 'html.parser', from_encoding='utf-8')
    try:
        main = soup.find('div', attrs={'id':'wrapper'}).find('div', attrs={'id':'root'}).find('div', attrs={'id':'main'})
        try:
            title = main.find('div', class_='subpage_title_block').find('h3').find('a').text.strip()
        except Exception as e:
            print(f'Title block Exception: url={url}')
            title = ''
        try:
            cast_elems = main.find('div', class_='header', attrs={'id':'fullcredits_content'})
            cast_h4 = cast_elems.find_all('h4')
            cast_table = cast_elems.find_all('table')
        except Exception as e:
            error_msg = f'Cast block Exception: url={url}, msg={e}'
            write_cast_error_log(ind, url, error_msg)
            print(ind, error_msg)
        if mtype in ['TV Series', 'TV Mini Series']:
            full_list = parse_series(cast_table, cast_h4, imdb_url, title, year, ind)
        else:
            full_list = parse_movies(cast_table, cast_h4, imdb_url, title, year, ind)
        for data in full_list:
            write_cast_data(data)
    except Exception as e:
        error_msg = f'Content block Exception: url={url}, e={e}'
        write_cast_error_log(ind, url, error_msg)
        print(ind, error_msg)

#parsed

In [ ]:
def write_cast_data(data):
    with open('imdb_casts_unparsed_50000.csv','a') as f:
        writer = csv.writer(f)
        writer.writerow((
            data['url'],
            data['title'],
            data['department'],
            data['name'],
            data['position'],
            data['comment'],
            data['episodes'],
            data['year'],
            data['credited'],
            data['rating'],
            data['name_ref']
            ))

In [ ]:
def separated_position(position):
    """
    Separates position, comment and credited from a string

    Args:
        position (str): full line of position/role.

    Returns:
       data (list): list of dicts in separated lines
    """
    #Checking whether person worked for several positions
    data = []
    comment = ''
    if '/ ...' in position:
        position = position.replace('/ ...', '').strip()
    if ' / ' not in position:
        if ':' in position:
            pos = position.split(':')[0]
            comment = ', '.join(position.split(':')[1:])
            position, comment = pos.strip(), comment.strip()
        position, comment, credited = separated_position_comments_credits(position, comment)
        if 'uncredited' in comment.lower():
            comment = comment.replace('uncredited', '').replace('(', '').replace(')', '').strip()
            credited = 'Uncredited'
        elif '(as ' in comment.lower():
            if comment.count('(as') == 1:
                comment, credited = comment.split('(as ')
                credited = credited.replace(')', '').strip()
                comment = comment.strip()
            elif comment.count('(as') == 2:
                comment, credited = comment.split('(as ')[0], ', '.join([com.strip() for com in comment.split('(as')[1:]])
                credited = credited.replace(')', '').strip()
                comment = comment.strip()
        data.append({'position':position, 'comment':comment, 'credited':credited})
    else:
        sep_position = position.split(' / ')
        for pos in sep_position:
            if ':' in pos:
                position = pos.split(':')[0]
                comment = ', '.join(pos.split(':')[1:])
                position, comment = position.strip(), comment.strip()
                position, comment, credited = separated_position_comments_credits(position, comment)
                if 'uncredited' in comment.lower():
                    comment = comment.replace('uncredited', '').replace('(', '').replace(')', '').strip()
                    credited = 'Uncredited'
                elif '(as ' in comment.lower():
                    if comment.count('(as') == 1:
                        comment, credited = comment.split('(as ')
                        credited = credited.replace(')', '').strip()
                        comment = comment.strip()
                    elif comment.count('(as') == 2:
                        comment, credited = comment.split('(as ')[0], ', '.join([com.strip() for com in comment.split('(as')[1:]])
                        credited = credited.replace(')', '').strip()
                        comment = comment.strip()
                data.append({'position':position, 'comment':comment, 'credited':credited})
            else:
                position, comment = pos.strip(), ''
                position, comment, credited = separated_position_comments_credits(position, comment)
                if 'uncredited' in comment.lower():
                    comment = comment.replace('uncredited', '').replace('(', '').replace(')', '').strip()
                    credited = 'Uncredited'
                elif '(as ' in comment.lower():
                    if comment.count('(as') == 1:
                        comment, credited = comment.split('(as ')
                        credited = credited.replace(')', '').strip()
                        comment = comment.strip()
                    elif comment.count('(as') == 2:
                        comment, credited = comment.split('(as ')[0], ', '.join([com.strip() for com in comment.split('(as')[1:]])
                        credited = credited.replace(')', '').strip()
                        comment = comment.strip()
                data.append({'position':position, 'comment':comment, 'credited':credited})
    return data

def separated_position_comments_credits(position, comment):
    credited = ''
    #Checking whether the person is uncredited
    if 'uncredited' in position.lower():
        position = position.replace('uncredited', '').replace('(', '').replace(')', '').strip()
        credited = 'Uncredited'
    #Checking whether the person is credited under other name
    elif '(as ' in position:
        if position.count('(as') == 1:
            position, credited = position.split('(as ')
            credited = credited.replace(')', '').strip()
            position = position.strip()
        elif position.count('(as') == 2:
            position, credited = position.split('(as ')[0], ', '.join([com.strip() for com in position.split('(as')[1:]])
            credited = credited.replace(')', '').strip()
            position = position.strip()
    elif '(As ' in position:
        position, credited = position.split('(As ')
        credited = credited.replace(')', '').strip()
        position = position.strip()
    elif 'singing voice' in position and 'additional' not in position:
        position = position.replace('singing voice', '').strip()
        comment = 'singing voice'
    elif 'voice' in position and 'additional' not in position:
        position = position.replace('voice', '').strip()
        comment = 'voice'


    if '(' in position:
        position = position.replace(')', '').replace('(', '').strip()
    else:
        position = position.strip()
    return position, comment, credited

def separated_episodes(episodes, year):
    if 'unknown episodes' not in episodes:
        try:
            episodes, year = episodes.split(', ')
            episodes = episodes.replace('(', '').replace(')', '').strip()
            year = year.replace('(', '').replace(')', '').strip()
        except Exception as e:
            episodes = episodes.replace('(', '').replace(')', '').strip()
            year = year.replace('(', '').replace(')', '').strip()
    else:
        episodes = 'unknown episodes'
    return episodes, year

In [ ]:
def parse_series(cast_table, cast_h4, imdb_url, title, year, ind):
    full_list = []
    for i in range(len(cast_h4)):
        h4, table = cast_h4[i], cast_table[i]
        department = h4.text.strip().replace('\n      ', '').replace('\n', '')
        info = table.find_all('tr')
        #print(department)
        if 'Cast' in department and 'Casting' not in department:
            for j in range(1, len(info)):
                tds = info[j].find_all('td')
                if len(tds)>1:
                    rating = j
                    try:
                        name = tds[1].find('a').text.strip()
                        name_ref = imdb_url + tds[1].find('a')['href']
                    except Exception as e:
                        error_msg = f'Name block exception: url={url}, dep={department} | {e}'
                        write_cast_error_log(ind, url, error_msg)
                        print(ind, error_msg)
                    try:
                        href = tds[3].find_all('a')
                        #print(href)
                        episodes = ''

                        if href[0].text.strip() != href[-1].text.strip():
                            full_position = href[0].text.strip() +  ' ' + href[-1].text.strip()
                        else:
                            full_position = href[-1].text
                        #print(full_position)
                        # episodes, year = separated_episodes(episodes, year)
                        # data = separated_position(position)
                        try:
                            m = re.search(r'\(*\d* episodes*,* *\d*-*\d*\)*', full_position)
                            y = re.search(r'\(*\d{4}\)*', full_position)
                            if '(unknown episodes)' in full_position or 'unknown episodes' in full_position:
                                episodes = 'unknown episodes'
                            elif m:
                                episodes = m.group(0)
                            elif y:
                                episodes = ''
                                year = y.group(0)
                                full_position = full_position.replace(year, '').strip()
                            else:
                                episodes = ''
                            position = full_position.replace(episodes, '').strip()
                            data = separated_position(position)
                            episodes, year = separated_episodes(episodes, year)
                            for dct in data:
                                d = {'url':url, 'title':title, 'department': department,
                                    'name':name, 'position':dct['position'],
                                    'comment': dct['comment'], 'episodes':episodes,
                                    'year':year, 'credited': dct['credited'],
                                    'rating':rating, 'name_ref':name_ref}
                                full_list.append(d)
                                #print(d)
                        except Exception as e:
                            error_msg = f'Position block exception: url={url}, dep={department}, name={name} | {e}'
                            write_cast_error_log(ind, url, error_msg)
                            print(ind, error_msg)
                            continue

                    except Exception as e:
                        try:
                            href = tds[3].find_all('a')
                            episodes = href[0].text
                            data = [{'position':'', 'comment':'', 'credited':''}]
                            episodes, year = separated_episodes(episodes, year)
                        except Exception as e:
                            error_msg = f'Position block exception: url={url}, dep={department}, name={name} | {e}'
                            write_cast_error_log(ind, url, error_msg)
                            print(ind, error_msg)
                            data = [{'position':'', 'comment':'', 'credited':''}]
                            episodes = ''
                        for dct in data:
                            d = {'url':url, 'title':title, 'department': department,
                                'name':name, 'position':dct['position'],
                                'comment': dct['comment'], 'episodes':episodes,
                                'year':year, 'credited': dct['credited'],
                                'rating':rating, 'name_ref':name_ref}
                            full_list.append(d)
                            #print(d)
                else:
                    continue
        else:
            for j in range(len(info)):
                rating = j + 1
                tds = info[j].find_all('td')
                name = tds[0].find('a').text.strip()
                name_ref = imdb_url + tds[0].find('a')['href']
                try:
                    full_position = tds[2].text.strip()
                    try:
                        m = re.search(r'\(*\d* episodes*,* *\d*-*\d*\)*', full_position)
                        y = re.search(r'\(*\d{4}\)*', full_position)
                        if '(unknown episodes)' in full_position or 'unknown episodes' in full_position:
                            episodes = 'unknown episodes'
                        elif m:
                            episodes = m.group(0)
                        elif y:
                            episodes = ''
                            year = y.group(0)
                            full_position = full_position.replace(year, '').strip()
                        else:
                            episodes = ''
                        position = full_position.replace(episodes, '').strip()
                        data = separated_position(position)
                        episodes, year = separated_episodes(episodes, year)
                        for dct in data:
                            d = {'url':url, 'title':title, 'department': department,
                                'name':name, 'position':dct['position'],
                                'comment': dct['comment'], 'episodes':episodes,
                                'year':year, 'credited': dct['credited'],
                                'rating':rating, 'name_ref':name_ref}
                            full_list.append(d)
                            #print(d)
                    except Exception as e:
                        error_msg = f'Position block exception: url={url}, dep={department}, name={name} | {e}'
                        write_cast_error_log(ind, url, error_msg)
                        print(ind, error_msg)
                        continue
                except Exception:
                    d = {'url':url, 'title':title, 'department': department,
                         'name':name, 'position':'', 'comment': '', 'episodes':'',
                         'year':year, 'credited': '', 'rating':rating, 'name_ref':name_ref}
                    full_list.append(d)
    #print(full_list)
    return full_list

In [ ]:
def parse_movies(cast_table, cast_h4, imdb_url, title, year, ind):
    full_list = []
    for i in range(len(cast_table)):
        h4, table = cast_h4[i], cast_table[i]
        department = h4.text.strip().replace('\n      ', '').replace('\n', '')
        info = [tr for tr in table.find_all('tr') if tr.find('td', class_='name') is not None or\
                tr.find('td', class_='primary_photo') is not None]
        if 'Cast' in department and 'Casting' not in department:
            for j in range(len(info)):
                try:
                    row = info[j]
                    tds = row.find_all('td')
                    if len(tds)>1:
                        rating = j
                        name = tds[1].find('a').text.strip()
                        name_ref = imdb_url + tds[1].find('a')['href']
                        try:
                            position = tds[3].text.strip()
                            episodes = ''
                        except Exception as e:
                            position, episodes = '', ''
                        data = separated_position(position)
                        for dct in data:
                            d = {'url':url, 'title':title, 'department': department,
                                'name':name, 'position':dct['position'],
                                'comment': dct['comment'], 'episodes':episodes,
                                'year':year, 'credited': dct['credited'],
                                'rating':rating, 'name_ref':name_ref}
                            full_list.append(d)
                    else:
                        continue
                except Exception as e:
                    error_msg = f'Movie Actors Exception: url={url}, dep={department}, name={name} | {e}'
                    write_cast_error_log(ind, url, error_msg)
                    print(ind, error_msg)
                    continue
        else:
            for j in range(len(info)):
                try:
                    rating = j + 1
                    tds = info[j].find_all('td')
                    name = tds[0].find('a').text.strip()
                    name_ref = imdb_url + tds[0].find('a')['href']
                    try:
                        position = tds[2].text.strip()
                    except Exception as e:
                        position = ''
                    episodes = ''
                    data = separated_position(position)
                    for dct in data:
                        d = {'url':url, 'title':title, 'department': department,
                            'name':name, 'position':dct['position'],
                            'comment': dct['comment'], 'episodes':episodes,
                            'year':year, 'credited': dct['credited'],
                            'rating':rating, 'name_ref':name_ref}
                        full_list.append(d)
                except Exception as e:
                    error_msg = f'Movie Cast Exception: url={url}, dep={department}, name={name} | {e}'
                    write_cast_error_log(ind, url, error_msg)
                    print(ind, error_msg)
                    continue
    return full_list

In [ ]:
def write_cast_error_log(i, url, error_log):
    with open('error_cast_log_unp.txt', 'a') as f:
        f.write(f'{i} | {url} | {error_log} \n')
    with open('error_cast_urls_unp.txt', 'a') as f:
        f.write(url + '\n')

In [ ]:
def get_cast_data(html, url, mtype, year, ind):
    imdb_url = 'https://www.imdb.com'
    soup = BeautifulSoup(html, 'html.parser', from_encoding='utf-8')
    try:
        main = soup.find('div', attrs={'id':'main'})
        #print(main)
        try:
            title = main.find('div', class_='subpage_title_block').find('div', class_="subpage_title_block__right-column").find('h3').find('a').text.strip()
            #print(title)
        except Exception as e:
            print(f'Title block Exception: url={url}')
            title = ''
        try:
            cast_elems = main.find('div', class_='header', attrs={'id':'fullcredits_content'})
            #print(1)
            cast_h4 = cast_elems.find_all('h4')
            #print(cast_elems)
            cast_table = cast_elems.find_all('table')
        except Exception as e:
            error_msg = f'Cast block Exception: url={url}, msg={e}'
            write_cast_error_log(ind, url, error_msg)
            print(ind, error_msg)
        if mtype in ['TV Series', 'TV Mini Series']:
            full_list = parse_series(cast_table, cast_h4, imdb_url, title, year, ind)
            #print(full_list)
        else:
            full_list = parse_movies(cast_table, cast_h4, imdb_url, title, year, ind)
        for data in full_list:
           print(data)
           write_cast_data(data)
           pass
    except Exception as e:
        error_msg = f'Content block Exception: url={url}, title={title} e={e}'
        write_cast_error_log(ind, url, error_msg)
        print(ind, error_msg)

In [ ]:
#drama_titles.append('https://www.imdb.com/title/tt0808357/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_lust')
#user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
ua = UserAgent()
#user_agent = ua.random
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'
for i in range(0, 1):
    url = 'https://www.imdb.com/title/tt3259100/fullcredits/?ref_=tt_cst_sm'
    mtype = 'TV Series'
    year = '2011– '
    response = requests.get(url,
                            headers={'Accept-Language': 'en-US,en;q=0.9',
                                     'User-Agent':user_agent})
    for key, value in response.request.headers.items():
        print(key+": "+value)
    print(i, url)
    html = response.content.decode('utf-8')
    get_cast_data(html, url, mtype, year, i)
    time.sleep(1)

NameError: name 'UserAgent' is not defined

In [ ]:
ua = UserAgent()
ua.getBrowser('google')

WARNING:fake_useragent:Error occurred during getting browser(s): google, but was suppressed with fallback.

{'useragent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0',
 'percent': 100.0,
 'type': 'desktop',
 'device_brand': None,
 'browser': 'Edge',
 'browser_version': '122.0.0.0',
 'browser_version_major_minor': 122.0,
 'os': 'win32',
 'os_version': '10',
 'platform': 'Win32'}

In [ ]:
os.getcwd()

'/content/drive/MyDrive/Bot/Parsing'

In [ ]:
csv_files = ['imdb_casts_unparsed.csv', 'imdb_casts_unparsed_10000.csv', 'imdb_casts_unparsed_20000.csv',
             'imdb_casts_unparsed_30000.csv', 'imdb_casts_unparsed_40000.csv', 'imdb_casts_unparsed_50000.csv']
dataframes = []

# Читаем каждый CSV файл и добавляем его в список
for file in csv_files:
    df = pd.read_csv(file, names=[str(i) for i in range(11)])
    dataframes.append(df)

# Объединяем все DataFrame'ы в один
df = pd.concat(dataframes, ignore_index=True)

In [ ]:
result.to_csv('cleaned_unparsed.csv', index=False)

In [ ]:
df_present.head(50)

,0,1,2,3,4,5,6,7,8,9,10
42825,https://www.imdb.com/title/tt32525811/fullcred...,"Present, Is Present",Series Directed by,Huang Yuanda,NaN,NaN,NaN,2024-,NaN,1,https://www.imdb.com/name/nm9751809/?ref_=ttfc...
42826,https://www.imdb.com/title/tt32525811/fullcred...,"Present, Is Present",Series Cast,Tu Bing,NaN,NaN,NaN,2024-,NaN,1,https://www.imdb.com/name/nm16223494/?ref_=ttf...
42827,https://www.imdb.com/title/tt32525811/fullcred...,"Present, Is Present",Series Cast,Fan Zhi Xin,NaN,NaN,NaN,2024-,NaN,2,https://www.imdb.com/name/nm16223493/?ref_=ttf...
42828,https://www.imdb.com/title/tt32525811/fullcred...,"Present, Is Present",Series Cast,Song Yi Xiong,NaN,NaN,NaN,2024-,NaN,3,https://www.imdb.com/name/nm16223495/?ref_=ttf...

In [ ]:
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
for i in range(0, len(df)):
    url = df['url'][i]
    mtype = df['mtype'][i]
    year = df['year'][i]
    try:
        response = requests.get(url,
                                headers={'Accept-Language': 'en-US,en;q=0.9',
                                         'User-Agent':user_agent})
        print(i, url)
        html = response.content.decode('utf-8')
        get_cast_data(html, url, mtype, year, i)
    except Exception as e:
        error_msg = f'{i} | {url} | e={e}'
        print(error_msg)
        write_cast_error_log(i, url, error_msg)
    time.sleep(1)

44000 https://www.imdb.com/title/tt3846642/fullcredits/?ref_=tt_cst_sm
44001 https://www.imdb.com/title/tt7243750/fullcredits/?ref_=tt_cst_sm
44002 https://www.imdb.com/title/tt0098328/fullcredits/?ref_=tt_cst_sm
44003 https://www.imdb.com/title/tt11968256/fullcredits/?ref_=tt_cst_sm
44004 https://www.imdb.com/title/tt13183494/fullcredits/?ref_=tt_cst_sm
44005 https://www.imdb.com/title/tt0052391/fullcredits/?ref_=tt_cst_sm
44006 https://www.imdb.com/title/tt11727058/fullcredits/?ref_=tt_cst_sm
44007 https://www.imdb.com/title/tt1942887/fullcredits/?ref_=tt_cst_sm
44008 https://www.imdb.com/title/tt0236285/fullcredits/?ref_=tt_cst_sm
44009 https://www.imdb.com/title/tt21629052/fullcredits/?ref_=tt_cst_sm
44010 https://www.imdb.com/title/tt0804484/fullcredits/?ref_=tt_cst_sm
44011 https://www.imdb.com/title/tt1097239/fullcredits/?ref_=tt_cst_sm
44012 https://www.imdb.com/title/tt12787842/fullcredits/?ref_=tt_cst_sm
44013 https://www.imdb.com/title/tt0396184/fullcredits/?ref_=tt_cst_sm
44014 https://www.imdb.com/title/tt0146971/fullcredits/?ref_=tt_cst_sm
44015 https://www.imdb.com/title/tt1912888/fullcredits/?ref_=tt_cst_sm
44016 https://www.imdb.com/title/tt4507428/fullcredits/?ref_=tt_cst_sm
44017 https://www.imdb.com/title/tt4051832/fullcredits/?ref_=tt_cst_sm
44018 https://www.imdb.com/title/tt17274522/fullcredits/?ref_=tt_cst_sm
44019 https://www.imdb.com/title/tt1384790/fullcredits/?ref_=tt_cst_sm
44020 https://www.imdb.com/title/tt7614908/fullcredits/?ref_=tt_cst_sm
44021 https://www.imdb.com/title/tt0100994/fullcredits/?ref_=tt_cst_sm
44022 https://www.imdb.com/title/tt0097707/fullcredits/?ref_=tt_cst_sm
44023 https://www.imdb.com/title/tt5612212/fullcredits/?ref_=tt_cst_sm
44024 https://www.imdb.com/title/tt0064088/fullcredits/?ref_=tt_cst_sm
44025 https://www.imdb.com/title/tt0361436/fullcredits/?ref_=tt_cst_sm
44026 https://www.imdb.com/title/tt6715232/fullcredits/?ref_=tt_cst_sm
44027 https://www.imdb.com/title/tt0283714/fullcredits/?ref_=tt_cst_sm
44028 https://www.imdb.com/title/tt12587880/fullcredits/?ref_=tt_cst_sm
44029 https://www.imdb.com/title/tt0079937/fullcredits/?ref_=tt_cst_sm
44030 https://www.imdb.com/title/tt0052121/fullcredits/?ref_=tt_cst_sm
44031 https://www.imdb.com/title/tt28618542/fullcredits/?ref_=tt_cst_sm
44032 https://www.imdb.com/title/tt5956100/fullcredits/?ref_=tt_cst_sm
44033 https://www.imdb.com/title/tt30839571/fullcredits/?ref_=tt_cst_sm
44034 https://www.imdb.com/title/tt2278245/fullcredits/?ref_=tt_cst_sm
44035 https://www.imdb.com/title/tt2051741/fullcredits/?ref_=tt_cst_sm
44036 https://www.imdb.com/title/tt1753783/fullcredits/?ref_=tt_cst_sm
44037 https://www.imdb.com/title/tt26928684/fullcredits/?ref_=tt_cst_sm
44038 https://www.imdb.com/title/tt9051908/fullcredits/?ref_=tt_cst_sm
44039 https://www.imdb.com/title/tt11423818/fullcredits/?ref_=tt_cst_sm
44040 https://www.imdb.com/title/tt1389072/fullcredits/?ref_=tt_cst_sm
44041 https://www.imdb.com/title/tt33436942/fullcredits/?ref_=tt_cst_sm
44042 https://www.imdb.com/title/tt6712390/fullcredits/?ref_=tt_cst_sm
44043 https://www.imdb.com/title/tt26924748/fullcredits/?ref_=tt_cst_sm
44044 https://www.imdb.com/title/tt0068148/fullcredits/?ref_=tt_cst_sm
44045 https://www.imdb.com/title/tt0403118/fullcredits/?ref_=tt_cst_sm
44046 https://www.imdb.com/title/tt7369974/fullcredits/?ref_=tt_cst_sm
44047 https://www.imdb.com/title/tt0054416/fullcredits/?ref_=tt_cst_sm
44048 https://www.imdb.com/title/tt0845746/fullcredits/?ref_=tt_cst_sm
44049 https://www.imdb.com/title/tt0035151/fullcredits/?ref_=tt_cst_sm
44050 https://www.imdb.com/title/tt25660990/fullcredits/?ref_=tt_cst_sm
44051 https://www.imdb.com/title/tt10954984/fullcredits/?ref_=tt_cst_sm
44051 Movie Cast Exception: url=https://www.imdb.com/title/tt10954984/fullcredits/?ref_=tt_cst_sm, dep=Visual Effects by, name=Gabrielle Lavoie-Gregoire | not enough values to unpack (expected 2, got 1)
44052 https://www.imdb.com/title/tt25274120/fullcredits/?ref_=tt_cst_sm
44053 https://www.imdb.com/title/tt14081460/fullcredits/?ref_=tt_cst_sm
44054 https://www.imdb.com/title/tt1636844/fullcredits/?ref_=tt_cst_sm
44055 https://www.imdb.com/title/tt0037330/fullcredits/?ref_=tt_cst_sm
44056 https://www.imdb.com/title/tt23334616/fullcredits/?ref_=tt_cst_sm
44057 https://www.imdb.com/title/tt0184144/fullcredits/?ref_=tt_cst_sm
44058 https://www.imdb.com/title/tt15776622/fullcredits/?ref_=tt_cst_sm
44059 https://www.imdb.com/title/tt1399664/fullcredits/?ref_=tt_cst_sm
44060 https://www.imdb.com/title/tt0069841/fullcredits/?ref_=tt_cst_sm
44061 https://www.imdb.com/title/tt0103696/fullcredits/?ref_=tt_cst_sm
44062 https://www.imdb.com/title/tt17737850/fullcredits/?ref_=tt_cst_sm
44063 https://www.imdb.com/title/tt33058359/fullcredits/?ref_=tt_cst_sm
44064 https://www.imdb.com/title/tt15509598/fullcredits/?ref_=tt_cst_sm
44065 https://www.imdb.com/title/tt0080928/fullcredits/?ref_=tt_cst_sm
44066 https://www.imdb.com/title/tt2637848/fullcredits/?ref_=tt_cst_sm
44067 https://www.imdb.com/title/tt7700788/fullcredits/?ref_=tt_cst_sm
44068 https://www.imdb.com/title/tt8709288/fullcredits/?ref_=tt_cst_sm
44069 https://www.imdb.com/title/tt0800341/fullcredits/?ref_=tt_cst_sm
44070 https://www.imdb.com/title/tt11542920/fullcredits/?ref_=tt_cst_sm
44071 https://www.imdb.com/title/tt23382644/fullcredits/?ref_=tt_cst_sm
44072 https://www.imdb.com/title/tt0368228/fullcredits/?ref_=tt_cst_sm
44073 https://www.imdb.com/title/tt10726456/fullcredits/?ref_=tt_cst_sm
44074 https://www.imdb.com/title/tt0092105/fullcredits/?ref_=tt_cst_sm
44075 https://www.imdb.com/title/tt2005302/fullcredits/?ref_=tt_cst_sm
44076 https://www.imdb.com/title/tt10350562/fullcredits/?ref_=tt_cst_sm
44077 https://www.imdb.com/title/tt0494185/fullcredits/?ref_=tt_cst_sm
44078 https://www.imdb.com/title/tt8660788/fullcredits/?ref_=tt_cst_sm
44079 https://www.imdb.com/title/tt7723394/fullcredits/?ref_=tt_cst_sm
44080 https://www.imdb.com/title/tt1971336/fullcredits/?ref_=tt_cst_sm
44081 https://www.imdb.com/title/tt0097239/fullcredits/?ref_=tt_cst_sm
44082 https://www.imdb.com/title/tt15660128/fullcredits/?ref_=tt_cst_sm
44083 https://www.imdb.com/title/tt0072812/fullcredits/?ref_=tt_cst_sm
44084 https://www.imdb.com/title/tt0835010/fullcredits/?ref_=tt_cst_sm
44085 https://www.imdb.com/title/tt3006472/fullcredits/?ref_=tt_cst_sm
44086 https://www.imdb.com/title/tt7239256/fullcredits/?ref_=tt_cst_sm
44087 https://www.imdb.com/title/tt0079002/fullcredits/?ref_=tt_cst_sm
44088 https://www.imdb.com/title/tt9803682/fullcredits/?ref_=tt_cst_sm
44089 https://www.imdb.com/title/tt19394168/fullcredits/?ref_=tt_cst_sm
44090 https://www.imdb.com/title/tt16088588/fullcredits/?ref_=tt_cst_sm
44091 https://www.imdb.com/title/tt2014230/fullcredits/?ref_=tt_cst_sm
44092 https://www.imdb.com/title/tt2066123/fullcredits/?ref_=tt_cst_sm
44093 https://www.imdb.com/title/tt0780548/fullcredits/?ref_=tt_cst_sm
44094 https://www.imdb.com/title/tt0038146/fullcredits/?ref_=tt_cst_sm
44095 https://www.imdb.com/title/tt2106675/fullcredits/?ref_=tt_cst_sm
44096 https://www.imdb.com/title/tt0001223/fullcredits/?ref_=tt_cst_sm
44097 https://www.imdb.com/title/tt4733426/fullcredits/?ref_=tt_cst_sm
44098 https://www.imdb.com/title/tt31889179/fullcredits/?ref_=tt_cst_sm
44099 https://www.imdb.com/title/tt4003070/fullcredits/?ref_=tt_cst_sm
44100 https://www.imdb.com/title/tt12965010/fullcredits/?ref_=tt_cst_sm
44101 https://www.imdb.com/title/tt5206628/fullcredits/?ref_=tt_cst_sm
44102 https://www.imdb.com/title/tt0260949/fullcredits/?ref_=tt_cst_sm
44103 https://www.imdb.com/title/tt15303180/fullcredits/?ref_=tt_cst_sm
44104 https://www.imdb.com/title/tt26470527/fullcredits/?ref_=tt_cst_sm
44105 https://www.imdb.com/title/tt0819755/fullcredits/?ref_=tt_cst_sm
44106 https://www.imdb.com/title/tt4696764/fullcredits/?ref_=tt_cst_sm
44107 https://www.imdb.com/title/tt1568202/fullcredits/?ref_=tt_cst_sm
44108 https://www.imdb.com/title/tt0076451/fullcredits/?ref_=tt_cst_sm
44109 https://www.imdb.com/title/tt4003914/fullcredits/?ref_=tt_cst_sm
44110 https://www.imdb.com/title/tt0101476/fullcredits/?ref_=tt_cst_sm
44111 https://www.imdb.com/title/tt0069064/fullcredits/?ref_=tt_cst_sm
44112 https://www.imdb.com/title/tt0765481/fullcredits/?ref_=tt_cst_sm
44113 https://www.imdb.com/title/tt0995011/fullcredits/?ref_=tt_cst_sm
44114 https://www.imdb.com/title/tt29458284/fullcredits/?ref_=tt_cst_sm
44115 https://www.imdb.com/title/tt33028976/fullcredits/?ref_=tt_cst_sm
44116 https://www.imdb.com/title/tt6752848/fullcredits/?ref_=tt_cst_sm
44117 https://www.imdb.com/title/tt4196566/fullcredits/?ref_=tt_cst_sm
44118 https://www.imdb.com/title/tt1297301/fullcredits/?ref_=tt_cst_sm
44119 https://www.imdb.com/title/tt34344071/fullcredits/?ref_=tt_cst_sm
44120 https://www.imdb.com/title/tt0449471/fullcredits/?ref_=tt_cst_sm
44121 https://www.imdb.com/title/tt13298500/fullcredits/?ref_=tt_cst_sm
44122 https://www.imdb.com/title/tt0185275/fullcredits/?ref_=tt_cst_sm
44123 https://www.imdb.com/title/tt0073312/fullcredits/?ref_=tt_cst_sm
44124 https://www.imdb.com/title/tt30150229/fullcredits/?ref_=tt_cst_sm
44125 https://www.imdb.com/title/tt3541262/fullcredits/?ref_=tt_cst_sm
44126 https://www.imdb.com/title/tt9320140/fullcredits/?ref_=tt_cst_sm
44127 https://www.imdb.com/title/tt10375972/fullcredits/?ref_=tt_cst_sm
44128 https://www.imdb.com/title/tt7875488/fullcredits/?ref_=tt_cst_sm
44129 https://www.imdb.com/title/tt3971974/fullcredits/?ref_=tt_cst_sm
44130 https://www.imdb.com/title/tt0093978/fullcredits/?ref_=tt_cst_sm
44131 https://www.imdb.com/title/tt12409496/fullcredits/?ref_=tt_cst_sm
44132 https://www.imdb.com/title/tt3853992/fullcredits/?ref_=tt_cst_sm
44133 https://www.imdb.com/title/tt0336693/fullcredits/?ref_=tt_cst_sm
44134 https://www.imdb.com/title/tt0210432/fullcredits/?ref_=tt_cst_sm
44135 https://www.imdb.com/title/tt2960600/fullcredits/?ref_=tt_cst_sm
44136 https://www.imdb.com/title/tt0445865/fullcredits/?ref_=tt_cst_sm
44137 https://www.imdb.com/title/tt0272397/fullcredits/?ref_=tt_cst_sm
44138 https://www.imdb.com/title/tt1883661/fullcredits/?ref_=tt_cst_sm
44139 https://www.imdb.com/title/tt0284445/fullcredits/?ref_=tt_cst_sm
44140 https://www.imdb.com/title/tt1392197/fullcredits/?ref_=tt_cst_sm
44141 https://www.imdb.com/title/tt0106936/fullcredits/?ref_=tt_cst_sm
44142 https://www.imdb.com/title/tt14669108/fullcredits/?ref_=tt_cst_sm
44143 https://www.imdb.com/title/tt0120579/fullcredits/?ref_=tt_cst_sm
44144 https://www.imdb.com/title/tt1124394/fullcredits/?ref_=tt_cst_sm
44145 https://www.imdb.com/title/tt14992524/fullcredits/?ref_=tt_cst_sm
44146 https://www.imdb.com/title/tt1615156/fullcredits/?ref_=tt_cst_sm
44147 https://www.imdb.com/title/tt0143805/fullcredits/?ref_=tt_cst_sm
44148 https://www.imdb.com/title/tt30765303/fullcredits/?ref_=tt_cst_sm
44149 https://www.imdb.com/title/tt3240080/fullcredits/?ref_=tt_cst_sm
44150 https://www.imdb.com/title/tt1533435/fullcredits/?ref_=tt_cst_sm
44151 https://www.imdb.com/title/tt4777200/fullcredits/?ref_=tt_cst_sm
44152 https://www.imdb.com/title/tt4191580/fullcredits/?ref_=tt_cst_sm
44153 https://www.imdb.com/title/tt4687856/fullcredits/?ref_=tt_cst_sm
44154 https://www.imdb.com/title/tt10975258/fullcredits/?ref_=tt_cst_sm
44155 https://www.imdb.com/title/tt0061075/fullcredits/?ref_=tt_cst_sm
44156 https://www.imdb.com/title/tt3976016/fullcredits/?ref_=tt_cst_sm
44157 https://www.imdb.com/title/tt21216012/fullcredits/?ref_=tt_cst_sm
44158 https://www.imdb.com/title/tt15209992/fullcredits/?ref_=tt_cst_sm
44159 https://www.imdb.com/title/tt0089424/fullcredits/?ref_=tt_cst_sm
44160 https://www.imdb.com/title/tt0120265/fullcredits/?ref_=tt_cst_sm
44161 https://www.imdb.com/title/tt1264115/fullcredits/?ref_=tt_cst_sm
44162 https://www.imdb.com/title/tt1473357/fullcredits/?ref_=tt_cst_sm
44163 https://www.imdb.com/title/tt0051895/fullcredits/?ref_=tt_cst_sm
44164 https://www.imdb.com/title/tt0048919/fullcredits/?ref_=tt_cst_sm
44165 https://www.imdb.com/title/tt0300345/fullcredits/?ref_=tt_cst_sm
44166 https://www.imdb.com/title/tt26423054/fullcredits/?ref_=tt_cst_sm
44167 https://www.imdb.com/title/tt3009202/fullcredits/?ref_=tt_cst_sm
44168 https://www.imdb.com/title/tt10691888/fullcredits/?ref_=tt_cst_sm
44169 https://www.imdb.com/title/tt0948544/fullcredits/?ref_=tt_cst_sm
44170 https://www.imdb.com/title/tt8406738/fullcredits/?ref_=tt_cst_sm
44171 https://www.imdb.com/title/tt3892434/fullcredits/?ref_=tt_cst_sm
44172 https://www.imdb.com/title/tt14170710/fullcredits/?ref_=tt_cst_sm
44173 https://www.imdb.com/title/tt30195542/fullcredits/?ref_=tt_cst_sm
44174 https://www.imdb.com/title/tt1202625/fullcredits/?ref_=tt_cst_sm
44175 https://www.imdb.com/title/tt8452344/fullcredits/?ref_=tt_cst_sm
44176 https://www.imdb.com/title/tt2215151/fullcredits/?ref_=tt_cst_sm
44177 https://www.imdb.com/title/tt33482479/fullcredits/?ref_=tt_cst_sm
44178 https://www.imdb.com/title/tt26229554/fullcredits/?ref_=tt_cst_sm
44179 https://www.imdb.com/title/tt21383310/fullcredits/?ref_=tt_cst_sm
44180 https://www.imdb.com/title/tt10207180/fullcredits/?ref_=tt_cst_sm
44181 https://www.imdb.com/title/tt33369154/fullcredits/?ref_=tt_cst_sm
44182 https://www.imdb.com/title/tt27497507/fullcredits/?ref_=tt_cst_sm
44183 https://www.imdb.com/title/tt2429074/fullcredits/?ref_=tt_cst_sm
44184 https://www.imdb.com/title/tt21043376/fullcredits/?ref_=tt_cst_sm
44185 https://www.imdb.com/title/tt0107999/fullcredits/?ref_=tt_cst_sm
44186 https://www.imdb.com/title/tt2606924/fullcredits/?ref_=tt_cst_sm
44187 https://www.imdb.com/title/tt0415306/fullcredits/?ref_=tt_cst_sm
44188 https://www.imdb.com/title/tt0038458/fullcredits/?ref_=tt_cst_sm
44189 https://www.imdb.com/title/tt2182229/fullcredits/?ref_=tt_cst_sm
44190 https://www.imdb.com/title/tt0302909/fullcredits/?ref_=tt_cst_sm
44191 https://www.imdb.com/title/tt0178148/fullcredits/?ref_=tt_cst_sm
44192 https://www.imdb.com/title/tt9013980/fullcredits/?ref_=tt_cst_sm
44193 https://www.imdb.com/title/tt0041625/fullcredits/?ref_=tt_cst_sm
44194 https://www.imdb.com/title/tt2094787/fullcredits/?ref_=tt_cst_sm
44195 https://www.imdb.com/title/tt32436778/fullcredits/?ref_=tt_cst_sm
44196 https://www.imdb.com/title/tt8879858/fullcredits/?ref_=tt_cst_sm
44197 https://www.imdb.com/title/tt0084112/fullcredits/?ref_=tt_cst_sm
44198 https://www.imdb.com/title/tt0049278/fullcredits/?ref_=tt_cst_sm
44199 https://www.imdb.com/title/tt0179626/fullcredits/?ref_=tt_cst_sm
44200 https://www.imdb.com/title/tt3155428/fullcredits/?ref_=tt_cst_sm
44201 https://www.imdb.com/title/tt0291853/fullcredits/?ref_=tt_cst_sm
44202 https://www.imdb.com/title/tt22037872/fullcredits/?ref_=tt_cst_sm
44203 https://www.imdb.com/title/tt0883073/fullcredits/?ref_=tt_cst_sm
44204 https://www.imdb.com/title/tt22177770/fullcredits/?ref_=tt_cst_sm
44205 https://www.imdb.com/title/tt13131350/fullcredits/?ref_=tt_cst_sm
44206 https://www.imdb.com/title/tt0079963/fullcredits/?ref_=tt_cst_sm
44207 https://www.imdb.com/title/tt3775086/fullcredits/?ref_=tt_cst_sm
44208 https://www.imdb.com/title/tt0361227/fullcredits/?ref_=tt_cst_sm
44209 https://www.imdb.com/title/tt4048676/fullcredits/?ref_=tt_cst_sm
44210 https://www.imdb.com/title/tt1292575/fullcredits/?ref_=tt_cst_sm
44211 https://www.imdb.com/title/tt1869682/fullcredits/?ref_=tt_cst_sm
44212 https://www.imdb.com/title/tt0142972/fullcredits/?ref_=tt_cst_sm
44213 https://www.imdb.com/title/tt32481874/fullcredits/?ref_=tt_cst_sm
44214 https://www.imdb.com/title/tt0126004/fullcredits/?ref_=tt_cst_sm
44215 https://www.imdb.com/title/tt27201446/fullcredits/?ref_=tt_cst_sm
44216 https://www.imdb.com/title/tt1907668/fullcredits/?ref_=tt_cst_sm
44217 https://www.imdb.com/title/tt0329783/fullcredits/?ref_=tt_cst_sm
44218 https://www.imdb.com/title/tt17510870/fullcredits/?ref_=tt_cst_sm
44219 https://www.imdb.com/title/tt7831044/fullcredits/?ref_=tt_cst_sm
44220 https://www.imdb.com/title/tt15310816/fullcredits/?ref_=tt_cst_sm
44221 https://www.imdb.com/title/tt3986420/fullcredits/?ref_=tt_cst_sm
44222 https://www.imdb.com/title/tt0286049/fullcredits/?ref_=tt_cst_sm
44223 https://www.imdb.com/title/tt0090775/fullcredits/?ref_=tt_cst_sm
44224 https://www.imdb.com/title/tt10667026/fullcredits/?ref_=tt_cst_sm
44225 https://www.imdb.com/title/tt8430234/fullcredits/?ref_=tt_cst_sm
44226 https://www.imdb.com/title/tt0284330/fullcredits/?ref_=tt_cst_sm
44227 https://www.imdb.com/title/tt11394298/fullcredits/?ref_=tt_cst_sm
44228 https://www.imdb.com/title/tt6121356/fullcredits/?ref_=tt_cst_sm
44229 https://www.imdb.com/title/tt3746948/fullcredits/?ref_=tt_cst_sm
44230 https://www.imdb.com/title/tt7879372/fullcredits/?ref_=tt_cst_sm
44231 https://www.imdb.com/title/tt8783930/fullcredits/?ref_=tt_cst_sm
44232 https://www.imdb.com/title/tt0435665/fullcredits/?ref_=tt_cst_sm
44233 https://www.imdb.com/title/tt0498360/fullcredits/?ref_=tt_cst_sm
44234 https://www.imdb.com/title/tt0309820/fullcredits/?ref_=tt_cst_sm
44235 https://www.imdb.com/title/tt0089603/fullcredits/?ref_=tt_cst_sm
44236 https://www.imdb.com/title/tt17497958/fullcredits/?ref_=tt_cst_sm
44237 https://www.imdb.com/title/tt0077381/fullcredits/?ref_=tt_cst_sm
44238 https://www.imdb.com/title/tt8953768/fullcredits/?ref_=tt_cst_sm
44239 https://www.imdb.com/title/tt33540940/fullcredits/?ref_=tt_cst_sm
44240 https://www.imdb.com/title/tt18217272/fullcredits/?ref_=tt_cst_sm
44241 https://www.imdb.com/title/tt0039017/fullcredits/?ref_=tt_cst_sm
44242 https://www.imdb.com/title/tt0389651/fullcredits/?ref_=tt_cst_sm
44243 https://www.imdb.com/title/tt0103186/fullcredits/?ref_=tt_cst_sm
44244 https://www.imdb.com/title/tt33183838/fullcredits/?ref_=tt_cst_sm
44245 https://www.imdb.com/title/tt12630234/fullcredits/?ref_=tt_cst_sm
44246 https://www.imdb.com/title/tt0042046/fullcredits/?ref_=tt_cst_sm
44247 https://www.imdb.com/title/tt10050778/fullcredits/?ref_=tt_cst_sm
44248 https://www.imdb.com/title/tt0118556/fullcredits/?ref_=tt_cst_sm
44249 https://www.imdb.com/title/tt22000856/fullcredits/?ref_=tt_cst_sm
44250 https://www.imdb.com/title/tt11090316/fullcredits/?ref_=tt_cst_sm
44251 https://www.imdb.com/title/tt0301989/fullcredits/?ref_=tt_cst_sm
44252 https://www.imdb.com/title/tt23903930/fullcredits/?ref_=tt_cst_sm
44253 https://www.imdb.com/title/tt34728549/fullcredits/?ref_=tt_cst_sm
44254 https://www.imdb.com/title/tt11231226/fullcredits/?ref_=tt_cst_sm
44255 https://www.imdb.com/title/tt0095930/fullcredits/?ref_=tt_cst_sm
44256 https://www.imdb.com/title/tt0107504/fullcredits/?ref_=tt_cst_sm
44257 https://www.imdb.com/title/tt0096076/fullcredits/?ref_=tt_cst_sm
44258 https://www.imdb.com/title/tt5616176/fullcredits/?ref_=tt_cst_sm
44259 https://www.imdb.com/title/tt7243754/fullcredits/?ref_=tt_cst_sm
44260 https://www.imdb.com/title/tt0096073/fullcredits/?ref_=tt_cst_sm
44261 https://www.imdb.com/title/tt9852660/fullcredits/?ref_=tt_cst_sm
44262 https://www.imdb.com/title/tt0324681/fullcredits/?ref_=tt_cst_sm
44263 https://www.imdb.com/title/tt0097882/fullcredits/?ref_=tt_cst_sm
44264 https://www.imdb.com/title/tt0053146/fullcredits/?ref_=tt_cst_sm
44265 https://www.imdb.com/title/tt1196948/fullcredits/?ref_=tt_cst_sm
44266 https://www.imdb.com/title/tt6861980/fullcredits/?ref_=tt_cst_sm
44267 https://www.imdb.com/title/tt6598238/fullcredits/?ref_=tt_cst_sm
44268 https://www.imdb.com/title/tt31031708/fullcredits/?ref_=tt_cst_sm
44269 https://www.imdb.com/title/tt10778840/fullcredits/?ref_=tt_cst_sm
44270 https://www.imdb.com/title/tt27127187/fullcredits/?ref_=tt_cst_sm
44271 https://www.imdb.com/title/tt0070787/fullcredits/?ref_=tt_cst_sm
44272 https://www.imdb.com/title/tt1442411/fullcredits/?ref_=tt_cst_sm
44273 https://www.imdb.com/title/tt1124348/fullcredits/?ref_=tt_cst_sm
44274 https://www.imdb.com/title/tt4327424/fullcredits/?ref_=tt_cst_sm
44275 https://www.imdb.com/title/tt15208728/fullcredits/?ref_=tt_cst_sm
44276 https://www.imdb.com/title/tt28741881/fullcredits/?ref_=tt_cst_sm